# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/VM696/extract-files.sh

# HW init
PRODUCT_COPY_FILES += \
    vendor/lge/VM696/proprietary/qmuxd:/system/bin/qmuxd \
    vendor/lge/VM696/proprietary/hci_qcomm_init:/system/bin/hci_qcomm_init

# Sensors binaries
PRODUCT_COPY_FILES += \
    vendor/lge/VM696/proprietary/thermald:/system/bin/thermald

# other binaries
PRODUCT_COPY_FILES += \
    vendor/lge/VM696/proprietary/hostapd:/system/bin/hostapd \
    vendor/lge/VM696/proprietary/hostapd_cli:/system/bin/hostapd_cli \
    vendor/lge/VM696/proprietary/netmgrd:/system/bin/netmgrd \
    vendor/lge/VM696/proprietary/rmt_storage:/system/bin/rmt_storage \
    vendor/lge/VM696/proprietary/port-bridge:/system/bin/port-bridge \
    vendor/lge/VM696/proprietary/cnd:/system/bin/cnd \
    vendor/lge/VM696/proprietary/battery_charging:/system/bin/battery_charging \
    vendor/lge/VM696/proprietary/ATFWD-daemon:/system/bin/ATFWD-daemon \
    vendor/lge/VM696/proprietary/CKPD-daemon:/system/bin/CKPD-daemon \
    vendor/lge/VM696/proprietary/bridgemgrd:/system/bin/bridgemgrd \
    vendor/lge/VM696/proprietary/dun-server:/system/bin/dun-server \
    vendor/lge/VM696/proprietary/amploader:/system/bin/amploader \
    vendor/lge/VM696/proprietary/ds_fmc_appd:/system/bin/ds_fmc_appd \
    vendor/lge/VM696/proprietary/profiler_daemon:/system/bin/profiler_daemon \
    vendor/lge/VM696/proprietary/ccid_daemon:/system/bin/ccid_daemon \
    vendor/lge/VM696/proprietary/bridgeutil:/system/bin/bridgeutil \
    vendor/lge/VM696/proprietary/ptt_socket_app:/system/bin/ptt_socket_app \
    vendor/lge/VM696/proprietary/v4l2-qcamera-app:/system/bin/v4l2-qcamera-app \
    vendor/lge/VM696/proprietary/test_gemini:/system/bin/test_gemini \
    vendor/lge/VM696/proprietary/hciattach:/system/bin/hciattach \
    vendor/lge/VM696/proprietary/bluetoothd:/system/bin/bluetoothd \
    vendor/lge/VM696/proprietary/btwlancoex:/system/bin/btwlancoex \

# MM
#PRODUCT_COPY_FILES += \
#    vendor/lge/VM696/proprietary/mm-abl-test:/system/bin/mm-abl-test \
#    vendor/lge/VM696/proprietary/mm-adec-omxaac-test:/system/bin/mm-adec-omxaac-test \
#    vendor/lge/VM696/proprietary/mm-adec-omxadpcm-test:/system/bin/mm-adec-omxadpcm-test \
#    vendor/lge/VM696/proprietary/mm-adec-omxamr-test:/system/bin/mm-adec-omxamr-test \
#    vendor/lge/VM696/proprietary/mm-adec-omxamrwb-test:/system/bin/mm-adec-omxamrwb-test \
#    vendor/lge/VM696/proprietary/mm-adec-omxevrc-test:/system/bin/mm-adec-omxevrc-test \
#    vendor/lge/VM696/proprietary/mm-adec-omxmp3-test:/system/bin/mm-adec-omxmp3-test \
#    vendor/lge/VM696/proprietary/mm-adec-omxQcelp13-test:/system/bin/mm-adec-omxQcelp13-test \
#    vendor/lge/VM696/proprietary/mm-adec-omxwma-test:/system/bin/mm-adec-omxwma-test \
#    vendor/lge/VM696/proprietary/mm-aenc-omxaac-test:/system/bin/mm-aenc-omxaac-test \
#    vendor/lge/VM696/proprietary/mm-aenc-omxamr-test:/system/bin/mm-aenc-omxamr-test \
#    vendor/lge/VM696/proprietary/mm-aenc-omxevrc-test:/system/bin/mm-aenc-omxevrc-test \
#    vendor/lge/VM696/proprietary/mm-aenc-omxqcelp13-test:/system/bin/mm-aenc-omxqcelp13-test \
#    vendor/lge/VM696/proprietary/mm-audio-alsa-test:/system/bin/mm-audio-alsa-test \
#    vendor/lge/VM696/proprietary/mm-audio-ctrl-test:/system/bin/mm-audio-ctrl-test \
#    vendor/lge/VM696/proprietary/mm-audio-native-test:/system/bin/mm-audio-native-test \
#    vendor/lge/VM696/proprietary/mm-audio-voem_if-test:/system/bin/mm-audio-voem_if-test \
#    vendor/lge/VM696/proprietary/mm-jpeg-enc-test:/system/bin/mm-jpeg-enc-test \
#    vendor/lge/VM696/proprietary/mm-omx-devmgr:/system/bin/mm-omx-devmgr \
#    vendor/lge/VM696/proprietary/mm-qcamera-test:/system/bin/mm-qcamera-test \
#    vendor/lge/VM696/proprietary/mm-qcamera-daemon:/system/bin/mm-qcamera-daemon \
#    vendor/lge/VM696/proprietary/mm-qcamera-testsuite-client:/system/bin/mm-qcamera-testsuite-client \
#    vendor/lge/VM696/proprietary/mm-vdec-omx-test:/system/bin/mm-vdec-omx-test \
#    vendor/lge/VM696/proprietary/mm-venc-omx-test720p:/system/bin/mm-venc-omx-test720p \
#    vendor/lge/VM696/proprietary/mm-video-driver-test:/system/bin/mm-video-driver-test \
#    vendor/lge/VM696/proprietary/mm-video-encdrv-test:/system/bin/mm-video-encdrv-test \
#    vendor/lge/VM696/proprietary/libgemini.so:/system/lib/libgemini.so \
#    vendor/lge/VM696/proprietary/mm-adec-omxQcelpHw-test:/system/bin/mm-adec-omxQcelpHw-test \
#    vendor/lge/VM696/proprietary/mm-adec-omxvam-test:/system/bin/mm-adec-omxvam-test \
#    vendor/lge/VM696/proprietary/mm-audio-mvs-test:/system/bin/mm-audio-mvs-test \
#    vendor/lge/VM696/proprietary/mmc_test:/system/bin/mmc_test \
#    vendor/lge/VM696/proprietary/mm-jps-enc-test:/system/bin/mm-jps-enc-test \
#    vendor/lge/VM696/proprietary/mm-mpo-enc-test:/system/bin/mm-mpo-enc-test

PRODUCT_COPY_FILES += \
    vendor/lge/VM696/proprietary/mm-qcamera-test:/system/bin/mm-qcamera-test \
    vendor/lge/VM696/proprietary/libgemini.so:/system/lib/libgemini.so \
    vendor/lge/VM696/proprietary/mm-qcamera-daemon:/system/bin/mm-qcamera-daemon \
    vendor/lge/VM696/proprietary/mm-qcamera-testsuite-client:/system/bin/mm-qcamera-testsuite-client \

# SW
PRODUCT_COPY_FILES += \
    vendor/lge/VM696/proprietary/sw-adec-omxaac-test:/system/bin/sw-adec-omxaac-test \
    vendor/lge/VM696/proprietary/sw-adec-omxamr-test:/system/bin/sw-adec-omxamr-test \
    vendor/lge/VM696/proprietary/sw-adec-omxamrwb-test:/system/bin/sw-adec-omxamrwb-test \
    vendor/lge/VM696/proprietary/sw-adec-omxmp3-test:/system/bin/sw-adec-omxmp3-test

# egl
##PRODUCT_COPY_FILES += \
#    vendor/lge/VM696/proprietary/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
#    vendor/lge/VM696/proprietary/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
#    vendor/lge/VM696/proprietary/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
#    vendor/lge/VM696/proprietary/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
#    vendor/lge/VM696/proprietary/libgsl.so:/system/lib/libgsl.so \
#    vendor/lge/VM696/proprietary/libOpenVG.so:/system/lib/libOpenVG.so \
#    vendor/lge/VM696/proprietary/eglsubAndroid.so:/system/lib/egl/eglsubAndroid.so

# Camera
PRODUCT_COPY_FILES += \
    vendor/lge/VM696/proprietary/liboemcamera.so:/system/lib/liboemcamera.so \
    vendor/lge/VM696/proprietary/liboemcamera.so:/obj/lib/liboemcamera.so \
    vendor/lge/VM696/proprietary/libmmjpeg.so:/system/lib/libmmjpeg.so \
    vendor/lge/VM696/proprietary/libmmipl.so:/system/lib/libmmipl.so \
    vendor/lge/VM696/proprietary/libcamera.so:obj/lib/libcamera.so \
    vendor/lge/VM696/proprietary/libcamera.so:/system/lib/libcamera.so 

# Audio
PRODUCT_COPY_FILES += \
    vendor/lge/VM696/proprietary/libaudioalsa.so:/obj/lib/libaudioalsa.so \
    vendor/lge/VM696/proprietary/libaudioalsa.so:/system/lib/libaudioalsa.so \

# Sensors
PRODUCT_COPY_FILES += \
    vendor/lge/VM696/proprietary/sensors.default.so:/system/lib/hw/sensors.default.so \
    vendor/lge/VM696/proprietary/libacdapi_azi.so:/system/lib/libacdapi_azi.so

# GPS
PRODUCT_COPY_FILES += \
    vendor/lge/VM696/proprietary/libcommondefs.so:/obj/lib/libcommondefs.so \
    vendor/lge/VM696/proprietary/libcommondefs.so:/system/lib/libcommondefs.so \
    vendor/lge/VM696/proprietary/libgps.so:/system/lib/libgps.so \
    vendor/lge/VM696/proprietary/libloc_ext.so:/system/lib/libloc_ext.so \
    vendor/lge/VM696/proprietary/libloc_api-rpc-qc.so:/system/lib/libloc_api-rpc-qc.so \
    vendor/lge/VM696/proprietary/loc_api_app:/system/bin/loc_api_app \
#    vendor/lge/VM696/proprietary/gps.default.so:/system/lib/hw/gps.default.so

# OMX
PRODUCT_COPY_FILES += \
    vendor/lge/VM696/proprietary/libOmxEvrcEnc.so:/system/lib/libOmxEvrcEnc.so \
    vendor/lge/VM696/proprietary/libOmxAacDec.so:/system/lib/libOmxAacDec.so \
    vendor/lge/VM696/proprietary/libOmxQcelp13Dec.so:/system/lib/libOmxQcelp13Dec.so \
    vendor/lge/VM696/proprietary/libOmxAmrEnc.so:/system/lib/libOmxAmrEnc.so \
    vendor/lge/VM696/proprietary/libOmxAdpcmDec.so:/system/lib/libOmxAdpcmDec.so \
    vendor/lge/VM696/proprietary/libOmxEvrcDec.so:/system/lib/libOmxEvrcDec.so \
    vendor/lge/VM696/proprietary/libOmxAmrDec.so:/system/lib/libOmxAmrDec.so \
    vendor/lge/VM696/proprietary/libOmxAmrwbDec.so:/system/lib/libOmxAmrwbDec.so \
    vendor/lge/VM696/proprietary/libOmxWmaDec.so:/system/lib/libOmxWmaDec.so \
    vendor/lge/VM696/proprietary/libOmxQcelp13Enc.so:/system/lib/libOmxQcelp13Enc.so \
    vendor/lge/VM696/proprietary/libOmxMp3Dec.so:/system/lib/libOmxMp3Dec.so \
    vendor/lge/VM696/proprietary/libOmxAmrRtpDec.so:/system/lib/libOmxAmrRtpDec.so \
    vendor/lge/VM696/proprietary/libOmxAacEnc.so:/system/lib/libOmxAacEnc.so \
    vendor/lge/VM696/proprietary/libOmxQcelpHwDec.so:/system/lib/libOmxQcelpHwDec.so \
    vendor/lge/VM696/proprietary/libomx_aacdec_sharedlibrary.so:/system/lib/libomx_aacdec_sharedlibrary.so \
    vendor/lge/VM696/proprietary/libomx_amrdec_sharedlibrary.so:/system/lib/libomx_amrdec_sharedlibrary.so \
    vendor/lge/VM696/proprietary/libomx_amrenc_sharedlibrary.so:/system/lib/libomx_amrenc_sharedlibrary.so \
    vendor/lge/VM696/proprietary/libomx_avcdec_sharedlibrary.so:/system/lib/libomx_avcdec_sharedlibrary.so \
    vendor/lge/VM696/proprietary/libomx_m4vdec_sharedlibrary.so:/system/lib/libomx_m4vdec_sharedlibrary.so \
    vendor/lge/VM696/proprietary/libomx_mp3dec_sharedlibrary.so:/system/lib/libomx_mp3dec_sharedlibrary.so \
    vendor/lge/VM696/proprietary/libomx_sharedlibrary.so:/system/lib/libomx_sharedlibrary.so \
    vendor/lge/VM696/proprietary/libqcomm_omx.so:/system/lib/libqcomm_omx.so

# RIL
PRODUCT_COPY_FILES += \
    vendor/lge/VM696/proprietary/rild:/system/bin/rild \
    vendor/lge/VM696/proprietary/qmiproxy:/system/bin/qmiproxy \
    vendor/lge/VM696/proprietary/libril.so:/system/lib/libril.so \
    vendor/lge/VM696/proprietary/libreference-ril.so:/system/lib/libreference-ril.so \
    vendor/lge/VM696/proprietary/libril-qcril-hook-oem.so:/system/lib/libril-qcril-hook-oem.so \
    vendor/lge/VM696/proprietary/libdiag.so:/system/lib/libdiag.so \
    vendor/lge/VM696/proprietary/liboncrpc.so:/system/lib/liboncrpc.so \
    vendor/lge/VM696/proprietary/libnv.so:/system/lib/libnv.so \
    vendor/lge/VM696/proprietary/libril-qc-qmi-1.so:/system/lib/libril-qc-qmi-1.so \
    vendor/lge/VM696/proprietary/libqmi.so:/system/lib/libqmi.so \
    vendor/lge/VM696/proprietary/libdsm.so:/system/lib/libdsm.so \
    vendor/lge/VM696/proprietary/libqueue.so:/system/lib/libqueue.so \
    vendor/lge/VM696/proprietary/libpbmlib.so:/system/lib/libpbmlib.so \
    vendor/lge/VM696/proprietary/libdss.so:/system/lib/libdss.so \
    vendor/lge/VM696/proprietary/libqmiservices.so:/system/lib/libqmiservices.so \
    vendor/lge/VM696/proprietary/libqdp.so:/system/lib/libqdp.so \
    vendor/lge/VM696/proprietary/libidl.so:/system/lib/libidl.so \
    vendor/lge/VM696/proprietary/libdsutils.so:/system/lib/libdsutils.so \
    vendor/lge/VM696/proprietary/liboem_rapi.so:/system/lib/liboem_rapi.so \
    vendor/lge/VM696/proprietary/libdsi_netctrl.so:/system/lib/libdsi_netctrl.so \
    vendor/lge/VM696/proprietary/libpdsm_atl.so:/system/lib/libpdsm_atl.so \
    vendor/lge/VM696/proprietary/libnetmgr.so:/system/lib/libnetmgr.so \
    vendor/lge/VM696/proprietary/libpdapi.so:/system/lib/libpdapi.so \
    vendor/lge/VM696/proprietary/libdsnet.so:/system/lib/libdsnet.so \
    vendor/lge/VM696/proprietary/libdsprofile.so:/system/lib/libdsprofile.so \
    vendor/lge/VM696/proprietary/libdssock.so:/system/lib/libdssock.so \
    vendor/lge/VM696/proprietary/libmvs.so:/system/lib/libmvs.so \
    vendor/lge/VM696/proprietary/libping_mdm.so:/system/lib/libping_mdm.so \


# NFC
PRODUCT_COPY_FILES += \
    vendor/lge/VM696/proprietary/libpn544_fw.so:system/lib/libpn544_fw.so \
    vendor/lge/VM696/proprietary/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so \
#    vendor/lge/VM696/proprietary/libnfc_ndef.so:system/lib/libnfc_ndef.so \
#    vendor/lge/VM696/proprietary/libnfc.so:system/lib/libnfc.so
#    vendor/lge/VM696/proprietary/libnfc_jni.so:system/lib/libnfc_jni.so \

# Wifi
PRODUCT_COPY_FILES += \
vendor/lge/VM696/proprietary/libwcnftm.so:system/lib/libwcnftm.so \
vendor/lge/VM696/proprietary/libwfcu.so:system/lib/libwfcu.so \
vendor/lge/VM696/proprietary/WCN1314_cfg.dat:system/etc/firmware/wlan/volans/WCN1314_cfg.dat \
vendor/lge/VM696/proprietary/WCN1314_qcom_fw.bin:system/etc/firmware/wlan/volans/WCN1314_qcom_fw.bin \
vendor/lge/VM696/proprietary/WCN1314_qcom_cfg.ini:system/etc/wifi/WCN1314_qcom_cfg.ini \
vendor/lge/VM696/proprietary/WCN1314_qcom_wlan_nv.bin:system/etc/wifi/WCN1314_qcom_wlan_nv.bin \
vendor/lge/VM696/proprietary/ftm_ptt:system/bin/ftm_ptt \
vendor/lge/VM696/proprietary/ftmdaemon:system/bin/ftmdaemon \
vendor/lge/VM696/proprietary/WCN1314_qcom_wlan_nv.bin:system/etc/firmware/wlan/volans/WCN1314_qcom_wlan_nv.bin \
vendor/lge/VM696/proprietary/WCN1314_qcom_cfg.ini:system/etc/firmware/wlan/volans/WCN1314_qcom_cfg.ini \
vendor/lge/VM696/proprietary/wlan.ko:system/lib/modules/wlan.ko \
vendor/lge/VM696/proprietary/libqsap_sdk.so:system/lib/libqsap_sdk.so \
vendor/lge/VM696/proprietary/libQWiFiSoftApCfg.so:system/lib/libQWiFiSoftApCfg.so
#vendor/lge/VM696/proprietary/libQWiFiSoftApCfg.so:system/lib/libQWiFiSoftApCfg.so \
#vendor/lge/VM696/proprietary/ftmdaemon:system/bin/ftmdaemon 
# vendor/lge/VM696/proprietary/WCN1314_qcom_wlan_nv.bin:system/etc/firmware/wlan/volans/WCN1314_qcom_wlan_nv.bin \
#vendor/lge/VM696/proprietary/libwcnftm.so:system/lib/libwcnftm.so \
#vendor/lge/VM696/proprietary/WCN1314_qcom_fw.bin:system/etc/firmware/wlan/volans/WCN1314_qcom_fw.bin \

# Not sure yet or just lazy
PRODUCT_COPY_FILES += \
vendor/lge/VM696/proprietary/lights.msm7k.so:system/lib/hw/lights.msm7k.so \
vendor/lge/VM696/proprietary/copybit.msm7k.so:system/lib/hw/copybit.msm7k.so \
vendor/lge/VM696/proprietary/gralloc.msm7k.so:system/lib/hw/gralloc.msm7k.so \
vendor/lge/VM696/proprietary/lib_LG_fastaf.so:system/lib/lib_LG_fastaf.so \
vendor/lge/VM696/proprietary/libC2D2.so:system/lib/libC2D2.so \
vendor/lge/VM696/proprietary/libcne.so:system/lib/libcne.so \
vendor/lge/VM696/proprietary/libcneutils.so:system/lib/libcneutils.so \
vendor/lge/VM696/proprietary/librefcne.so:system/lib/librefcne.so \
vendor/lge/VM696/proprietary/libmmparser.so:system/lib/libmmparser.so

# Flash player
PRODUCT_COPY_FILES += \
vendor/lge/VM696/proprietary/libflashplayer.so:system/lib/plugins/com.adobe.flashplayer/libflashplayer.so \
vendor/lge/VM696/proprietary/libstagefright_froyo.so:system/lib/plugins/com.adobe.flashplayer/libstagefright_froyo.so \
vendor/lge/VM696/proprietary/libstagefright_honeycomb.so:system/lib/plugins/com.adobe.flashplayer/libstagefright_honeycomb.so \
vendor/lge/VM696/proprietary/libysshared.so:system/lib/plugins/com.adobe.flashplayer/libysshared.so


